### ISSUE TITLE
FileNotFoundError with edit_video_stitching_tuning.py (Windows)

### ISSUE THREAD

**Issue by sheseagle** [rotemtzaban/STIT#13]
Hello, I have been trying to install on Windows using Anaconda. I think I managed to install all the requirements, and I tried to run a test of Old Jim, and the test returned this error:

` File "...\STIT\utils\models_utils.py", line 21, in load_tuned_G
    with open(new_G_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/model_jim.pt'`

Can you help?

**Comment by rotemtzaban** [comment]
Hi,
Did you first run the inversion step as detailed here?: https://github.com/rotemtzaban/STIT#inversion
This is the step that creates the fine tuned generator, which we use to make the edits

**Comment by sheseagle** [comment]
Hey, yeah I hadn't done that part, I'm sorry. I decided to try again before answering you but I found another problem, here's the error:

```
Traceback (most recent call last):
  File "C:\Users\shese\Documents\DL\STIT\torch_utils\ops\upfirdn2d.py", line 32, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "C:\Users\shese\Documents\DL\STIT\torch_utils\custom_ops.py", line 64, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "C:\Users\shese\Documents\DL\STIT\torch_utils\custom_ops.py".

  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed
```

I've looked for solutions on other githubs, but everything I've tried still doesn't work.  I decided to send you here even though it could be another small thing I missed. (if you prefer I can open another #issue)

thank you in advance

**Comment by sheseagle** [comment]
Hey, yeah I hadn't done that part, I'm sorry. I decided to try again before answering you but I found another problem, here's the error:

```
Traceback (most recent call last):
  File "C:\...\DL\STIT\torch_utils\ops\upfirdn2d.py", line 32, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "C:\...\DL\STIT\torch_utils\custom_ops.py", line 64, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "C:\...\DL\STIT\torch_utils\custom_ops.py".

  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed
```

I've looked for solutions on other githubs, but everything I've tried still doesn't work. I decided to send you here even though it could be another small thing I missed. (if you prefer I can open another #issue)

thank you in advance

**Comment by rotemtzaban** [comment]
@sheseagle 
Hi, I believe from the error message the issue is that you don't have the compiler required to run Stylegan installed.
On windows, the compilation requires Visual Studio.
See here: https://github.com/NVlabs/stylegan2-ada-pytorch#requirements
You might want to look here as well: https://github.com/rotemtzaban/STIT/issues/11, as they faced similar issues with running on windows.
