### ISSUE TITLE
Click problems?

### ISSUE THREAD

**Issue by NoUserNameForYou** [rotemtzaban/STIT#25]
While trying to run the first inversion step I get this:

`Traceback (most recent call last):
  File "\STIT\train.py", line 124, in <module>
    main()
  File "\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "\ES\STIT\train.py", line 62, in main
    _main(**config, config=config)
  File "\ES\STIT\train.py", line 76, in _main
    files = make_dataset(input_folder)
  File "\ES\STIT\utils\data_utils.py", line 27, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: /data/obama is not a valid directory`

(removed the full path names due to privacy reasons)

I got this error while trying to install requirements.txt:

`qt5-tools 5.15.2.1.2 requires click~=7.0, but you have click 8.1.2 which is incompatible.`

I'm on Windows 11 with python 3.9.9 and cuda 11.6

If you could just release an easier way of doing this via Anaconda + template environment building file I'd be happy.

**Comment by rotemtzaban** [comment]
@NoUserNameForYou 

Hi,

Did you install the requirements on a clean environment? 
For me on a Linux machine it does not install qt5-tools, was that requirement installed via our requirements.txt?
Unfortunately I currently don't have a Windows machine to test on, so I can only test it on Linux.

**Comment by NoUserNameForYou** [comment]
I had a few things installed before. But shouldnt latest click work?

**Comment by rotemtzaban** [comment]
It does. It seems like the qt5-tools package is dependent on an older version of clip, which prevents the latest from being installed.

**Comment by NoUserNameForYou** [comment]
> It does. It seems like the qt5-tools package is dependent on an older version of clip, which prevents the latest from being installed.

Still the same error after "pip install --upgrade --no-deps --force-reinstall click" and even after uninstalling qt5 tools.

I ran "python train.py --input_folder /data/obama --output_folder training_results --run_name obama --num_pti_steps 80" in cmd btw. I don't know how to use the .py files as they have \ at the end of each line and they fail at 1st.

I give up until it becomes user friendly maybe with a virtual env., thanks for trying to help at least.
